# git configs
DSDEV_CONFIG_FPATH_NAME = "DSDEV_CONFIG_PATH"
DSDEV_CONFIG_FNAME = ".dsdev.cfg"
CONFIG_SEP = "/"
GIT_CONFIGS = "git"
GIT_ACCOUNT_ALIAS_DEFAULT = "account1"
GIT_ACCOUNT_LABEL = "GIT_ACCOUNT"
GIT_PAT_LABEL = "GIT_PAT"
